### ISSUE TITLE
Masklength range 32..32

### ISSUE THREAD

**Issue by jbemmel** [srl-labs/srl-rt5-l3evpn-basics-lab#1]
Nit picking
https://github.com/srl-labs/srl-l3evpn-basics-lab/blob/6c66bc4fde53da490f4ccc13fe4e9c3045a0809b/startup_configs/leaf1.conf#L34

```8..32``` is too broad

**Comment by hellt** [comment]
yeah, this is because I had to cover 10.10.10.10 loopback on the spine and 10.0.0.X/24 on leafs...

**Comment by jbemmel** [comment]
```prefix 10.0.0.0/8 mask-length-range 32..32``` also matches 10.10.10.10

**Comment by jbemmel** [comment]
Configs updated
